# Generated by Django 5.2.6 on 2025-09-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
